const king = "&#9818";
const queen = "&#9819";
const dragon = "&#128009";
const targaryenSigil =
  "https://awoiaf.westeros.org/images/thumb/1/1e/House_Targaryen.svg/218px-House_Targaryen.svg.png";
const baratheonSigil =
  "https://awoiaf.westeros.org/images/thumb/2/2d/House_Baratheon.svg/218px-House_Baratheon.svg.png";
const westerlingSigil =
  "https://awoiaf.westeros.org/images/thumb/f/f3/House_Westerling.svg/218px-House_Westerling.svg.png";
const costayneSigil =
  "https://awoiaf.westeros.org/images/thumb/6/69/House_Costayne.svg/218px-House_Costayne.svg.png";
const harrowaySigil =
  "https://awoiaf.westeros.org/images/thumb/a/ad/House_Harroway.svg/218px-House_Harroway.svg.png";
const hightowerSigil =
  "https://awoiaf.westeros.org/images/thumb/f/fe/House_Hightower.svg/218px-House_Hightower.svg.png";
const pentosSigil =
  "https://awoiaf.westeros.org/images/8/8a/Coin_of_Pentos.png";
const velaryonSigil =
  "https://awoiaf.westeros.org/images/thumb/5/5f/House_Velaryon.svg/218px-House_Velaryon.svg.png";
const arrynSigil =
  "https://awoiaf.westeros.org/images/thumb/b/b4/House_Arryn.svg/218px-House_Arryn.svg.png";
const farmanSigil =
  "https://awoiaf.westeros.org/images/thumb/1/1f/House_Farman.svg/218px-House_Farman.svg.png";
const royceSigil =
  "https://awoiaf.westeros.org/images/thumb/c/cf/House_Royce.svg/218px-House_Royce.svg.png";

export const data = [
  {
    id: 1,
    name: `Aegon I`,
    throne: king,
    gender: "male",
    dragon: "Balerion",
    dragonrider: dragon,
    culture: "Valyrian",
    Aliases: "Aegon the Conqueror",
    Born: "27 BC",
    Died: "37 AC",
    pids: [2, 3],
    img: "https://awoiaf.westeros.org/images/b/bc/Aegon_the_Conqueror.jpg",
    sigil: targaryenSigil,
  },
  {
    id: 2,
    name: `Visenya Targaryen`,
    throne: queen,
    gender: "female",
    dragon: "Vhagar",
    culture: "Valyrian",
    Aliases: null,
    Born: "28 BC or 29 BC",
    Died: "44 AC",
    pids: [1],
    img: "https://awoiaf.westeros.org/images/d/de/Visenya.jpg",
    sigil: targaryenSigil,
  },
  {
    id: 3,
    name: `Rhaenys Targaryen`,
    throne: queen,
    gender: "female",
    dragon: "Meraxes",
    culture: "Valyrian",
    Aliases: null,
    Born: "25 BC or 26 BC",
    Died: "10 AC",
    pids: [1],
    img: "https://awoiaf.westeros.org/images/8/82/Rhaenys.jpg",
    sigil: targaryenSigil,
  },

  {
    id: 4,
    name: "Maegor I",
    throne: king,
    gender: "male",
    dragon: "Balerion",
    culture: "",
    Aliases: ["Maegor the Cruel"],
    Born: "12 AC",
    Died: "48 AC",
    fid: 1,
    mid: 2,
    pids: [6, 7, 8, 9, 10],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/e/e3/MAEGOR_I.jpg",
  },
  {
    id: 5,
    name: "Aenys I",
    throne: king,
    gender: "male",
    dragon: "Quicksilver",
    culture: "Valyrian",
    Aliases: ["King Abomination"],
    Born: "7 AC",
    Died: "42 AC",
    fid: 1,
    mid: 3,
    pids: [11],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/d/d3/AENYS_I.jpg",
  },

  {
    id: 6,
    name: "Ceryse Hightower",
    throne: queen,
    gender: "female",
    dragon: null,
    culture: "",
    Aliases: null,
    Born: "2 AC",
    Died: "45 AC",
    pids: [4],
    sigil: hightowerSigil,
  },
  {
    id: 7,
    name: "Tyanna of the Tower",
    throne: queen,
    gender: "female",
    dragon: null,
    culture: "",
    Aliases: null,
    Born: "",
    Died: "48 AC",
    pids: [4],
    sigil: pentosSigil,
    img: "https://awoiaf.westeros.org/images/thumb/a/ad/Tyanna_of_Pentos_by_Samantha_Altarozzi.jpg/192px-Tyanna_of_Pentos_by_Samantha_Altarozzi.jpg",
  },
  {
    id: 8,
    name: "Alys Harroway",
    throne: queen,
    gender: "female",
    dragon: null,
    culture: "Rivermen",
    Aliases: null,
    Born: "",
    Died: "44 AC",
    fid: null,
    mid: null,
    pids: [4],
    sigil: harrowaySigil,
  },
  {
    id: 9,
    name: "Jeyne Westerling",
    throne: queen,
    gender: "female",
    dragon: null,
    culture: "Westerman",
    Aliases: null,
    Born: "27 AC",
    Died: "47 or 48 AC",
    pids: [4],
    sigil: westerlingSigil,
  },
  {
    id: 10,
    name: "Elinor Costayne",
    throne: queen,
    gender: "female",
    dragon: null,
    culture: "Reach",
    Aliases: ["Mother Elinor"],
    Born: "28 AC",
    Died: "",
    pids: [4],
    sigil: costayneSigil,
  },

  {
    id: 11,
    name: "Alyssa Velaryon",
    throne: queen,
    gender: "female",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "7 AC",
    Died: "54 AC",
    pids: [5, 12],
    sigil: velaryonSigil,
    img: "https://awoiaf.westeros.org/images/e/ee/Alyssa_Velaryon_by_Hylora.jpg",
  },
  {
    id: 12,
    name: "Rogar Baratheon",
    gender: "male",
    dragon: null,
    culture: "Stormlander",
    Aliases: null,
    Born: "17 AC",
    Died: "62 AC",
    pids: [11],
    sigil: baratheonSigil,
  },

  {
    id: 13,
    name: "Rhaena Targaryen",
    gender: "female",
    dragon: "Dreamfyre",
    culture: "Valyrian",
    Aliases: null,
    Born: "23 AC",
    Died: "73 AC",
    fid: 5,
    mid: 11,
    pids: [45],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/f/fe/Rhaena_by_Hylora.jpg/195px-Rhaena_by_Hylora.jpg",
  },
  {
    id: 14,
    name: "Rhaena Targaryen",
    gender: "female",
    dragon: "Dreamfyre",
    culture: "Valyrian",
    Aliases: null,
    Born: "23 AC",
    Died: "73 AC",
    // fid: 5,
    // mid: 11,
    pids: [15],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/f/fe/Rhaena_by_Hylora.jpg/195px-Rhaena_by_Hylora.jpg",
  },
  {
    id: 15,
    name: "Aegon Targaryen",
    gender: "male",
    dragon: "Quicksilver",
    culture: "Valyrian",
    Aliases: ["Aegon the Uncrowned"],
    Born: "26 AC",
    Died: "43 AC",
    fid: 5,
    mid: 11,
    pids: [14],
    sigil: targaryenSigil,
    img: "https://static.wikia.nocookie.net/gameofthrones/images/5/5c/Aegon_Targaryen_son_of_Aenys.png/",
  },
  {
    id: 45,
    name: "Androw Farman",
    gender: "male",
    dragon: null,
    culture: "Westermen",
    Aliases: null,
    Born: "32 AC",
    Died: "54 AC",
    pids: [13],
    sigil: farmanSigil,
  },
  {
    id: 16,
    name: "Viserys Targaryen",
    gender: "male",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "29 AC",
    Died: "44 AC",
    fid: 5,
    mid: 11,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/7/7d/Visrys_son_of_Aenys_by_Warpspeed.png/186px-Visrys_son_of_Aenys_by_Warpspeed.png",
  },
  {
    id: 17,
    name: "Jaehaerys I",
    throne: king,
    gender: "male",
    dragon: "Vermithor",
    culture: "Valyrian",
    Aliases: ["The Conciliator"],
    Born: "34 AC",
    Died: "103 AC",
    fid: 5,
    mid: 11,
    pids: [18],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/0/0a/JAEHAERYS_I.jpg",
  },
  {
    id: 18,
    name: "Alysanne Targaryen",
    throne: queen,
    gender: "female",
    dragon: "Silverwing",
    culture: "Valyrian",
    Aliases: ["Good Queen Alysanne"],
    Born: "36 AC",
    Died: "100 AC",
    fid: null,
    mid: null,
    pids: [17],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/5/55/Alysanne.jpg",
  },
  {
    id: 19,
    name: "Alysanne Targaryen",
    throne: queen,
    gender: "female",
    dragon: "Silverwing",
    culture: "Valyrian",
    Aliases: ["Good Queen Alysanne"],
    Born: "36 AC",
    Died: "100 AC",
    fid: 5,
    mid: 11,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/5/55/Alysanne.jpg",
  },
  {
    id: 20,
    name: "Vaella Targaryen",
    gender: "female",
    culture: "Valyrian",
    Aliases: [""],
    Born: "39 AC",
    Died: "39 AC",
    fid: 5,
    mid: 11,
    pids: [],
    sigil: targaryenSigil,
  },

  {
    id: 21,
    name: "Aerea Targaryen",
    gender: "female",
    dragon: "Balerion",
    culture: "Valyrian",
    Aliases: [""],
    Born: "42 AC",
    Died: "56 AC",
    fid: 15,
    mid: 14,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/a/ad/Aerea_3_by_Riotarttherite.png",
  },
  {
    id: 22,
    name: "Rhaella Targaryen",
    gender: "female",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "42 AC",
    Died: "73 AC",
    fid: 15,
    mid: 14,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/b/bf/Rhaella_daughter_of_Aegon_%282%29_by_Riotarttherite.png",
  },
  {
    id: 23,
    name: "Aegon Targaryen",
    gender: "male",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "52 AC",
    Died: "52 AC",
    fid: 17,
    mid: 18,
    pids: [],
    sigil: targaryenSigil,
  },
  {
    id: 24,
    name: "Daenarys Targaryen",
    gender: "female",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "53 AC",
    Died: "60 AC",
    fid: 17,
    mid: 18,
    pids: [],
    sigil: targaryenSigil,
  },
  {
    id: 25,
    name: "Aemon Targaryen",
    gender: "male",
    dragon: "Caraxes",
    culture: "Valyrian",
    Aliases: [""],
    Born: "55 AC",
    Died: "92 AC",
    fid: 17,
    mid: 18,
    pids: [37],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/2/28/Aemon_son_of_Jaehaerys_I_by_Riotarttherite.png/216px-Aemon_son_of_Jaehaerys_I_by_Riotarttherite.png",
  },
  {
    id: 26,
    name: "Baelon Targaryen",
    gender: "male",
    dragon: "Vhagar",
    culture: "Valyrian",
    Aliases: ["Baelon the Brave"],
    Born: "57 AC",
    Died: "101 AC",
    fid: 17,
    mid: 18,
    pids: [27],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/b/b4/Baelon_Targaryen_by_Riotarttherite.png/216px-Baelon_Targaryen_by_Riotarttherite.png",
  },
  {
    id: 27,
    name: "Alyssa Targaryen",
    gender: "female",
    dragon: "Meleys",
    culture: "Valyrian",
    Aliases: null,
    Born: "60 AC",
    Died: "84 AC",
    fid: null,
    mid: null,
    pids: [26],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/4/46/Alyssa_Targaryen_by_Paparinka_Art.jpg/196px-Alyssa_Targaryen_by_Paparinka_Art.jpg",
  },
  {
    id: 35,
    name: "Alyssa Targaryen",
    gender: "female",
    dragon: "Meleys",
    culture: "Valyrian",
    Aliases: null,
    Born: "60 AC",
    Died: "84 AC",
    fid: 17,
    mid: 18,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/4/46/Alyssa_Targaryen_by_Paparinka_Art.jpg/196px-Alyssa_Targaryen_by_Paparinka_Art.jpg",
  },
  {
    id: 28,
    name: "Maegelle Targaryen",
    gender: "female",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "62 AC",
    Died: "90 AC",
    fid: 17,
    mid: 18,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/4/49/Maegelle_Targaryen_by_Riotarttherite.png/200px-Maegelle_Targaryen_by_Riotarttherite.png",
  },
  {
    id: 29,
    name: "Vaegon Targaryen",
    gender: "male",
    dragon: null,
    culture: "Valyrian",
    Aliases: ["Vaegon the Dragonless"],
    Born: "63 AC",
    Died: "101 AC",
    fid: 17,
    mid: 18,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/8/8c/Vaegon_Targaryen_by_Jaydeewis.png/184px-Vaegon_Targaryen_by_Jaydeewis.png",
  },
  {
    id: 30,
    name: "Daella Targaryen",
    gender: "female",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "64 AC",
    Died: "82 AC",
    fid: 17,
    mid: 18,
    pids: [36],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/3/3b/Daella_Targaryen_%282%29_by_Riotarttherite.png/216px-Daella_Targaryen_%282%29_by_Riotarttherite.png",
  },
  {
    id: 31,
    name: "Saera Targaryen",
    gender: "female",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "67 AC",
    Died: "101 AC",
    fid: 17,
    mid: 18,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/8/8a/Saera_Targaryen_%282%29_by_Riotarttherite.png/216px-Saera_Targaryen_%282%29_by_Riotarttherite.png",
  },
  {
    id: 32,
    name: "Viserra Targaryen",
    gender: "female",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "71 AC",
    Died: "87 AC",
    fid: 17,
    mid: 18,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/1/10/Viserra_Targaryen_%282%29_by_Riotarttherite.png",
  },
  {
    id: 33,
    name: "Gaemon Targaryen",
    gender: "male",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "73 AC",
    Died: "74 AC",
    fid: 17,
    mid: 18,
    pids: [],
    sigil: targaryenSigil,
  },
  {
    id: 33,
    name: "Valerion Targaryen",
    gender: "male",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "77 AC",
    Died: "78 AC",
    fid: 17,
    mid: 18,
    pids: [],
    sigil: targaryenSigil,
  },
  {
    id: 34,
    name: "Gael Targaryen",
    gender: "female",
    dragon: null,
    culture: "Valyrian",
    Aliases: ["The Winter Child"],
    Born: "90 AC",
    Died: "99 AC",
    fid: 17,
    mid: 18,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/4/41/Gael_Targaryen_2_by_Riotarttherite.png/216px-Gael_Targaryen_2_by_Riotarttherite.png",
  },
  {
    id: 36,
    name: "Rodrik Arryn",
    gender: "male",
    dragon: null,
    culture: "Valemen",
    Aliases: null,
    Born: "44 AC",
    Died: "82-97 AC",
    fid: null,
    mid: null,
    pids: [30],
    sigil: arrynSigil,
  },
  {
    id: 37,
    name: "Jocelyn Baratheon",
    gender: "female",
    dragon: null,
    culture: "Stormlander",
    Aliases: null,
    Born: "54 AC",
    Died: "92-129 AC",
    fid: null,
    mid: null,
    pids: [25],
    sigil: baratheonSigil,
    img: "https://awoiaf.westeros.org/images/7/77/Jocelyn_Baratheon_by_Riotarttherite.png",
  },
  {
    id: 38,
    name: "Jocelyn Baratheon",
    gender: "female",
    dragon: null,
    culture: "Stormlander",
    Aliases: null,
    Born: "54 AC",
    Died: "92-129 AC",
    fid: 12,
    mid: 11,
    pids: [],
    sigil: baratheonSigil,
    img: "https://awoiaf.westeros.org/images/7/77/Jocelyn_Baratheon_by_Riotarttherite.png",
  },
  {
    id: 39,
    name: "Boremund Baratheon",
    gender: "male",
    dragon: null,
    culture: "Stormlander",
    Aliases: null,
    Born: "52 AC",
    Died: "101-129 AC",
    fid: 12,
    mid: 11,
    pids: [],
    sigil: baratheonSigil,
  },
  {
    id: 40,
    name: "Aemma Arryn",
    throne: queen,
    gender: "female",
    dragon: null,
    culture: "Valemen",
    Aliases: null,
    Born: "82 AC",
    Died: "105 AC",
    fid: 36,
    mid: 30,
    pids: [47],
    sigil: arrynSigil,
    img: "https://awoiaf.westeros.org/images/thumb/9/9f/Aemma_Arryn_and_Rhaenyra_Targaryen_by_Fkaluis.jpg/218px-Aemma_Arryn_and_Rhaenyra_Targaryen_by_Fkaluis.jpg",
  },
  {
    id: 41,
    name: "Rhaenys Targaryen",
    gender: "female",
    dragon: "Meleys",
    culture: "Valyrian",
    Aliases: ["The Queen Who Never Was"],
    Born: "74 AC",
    Died: "129 AC",
    fid: 25,
    mid: 37,
    pids: [46],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/9/96/Bella_Bergolts_The_Queen_Who_Never_Was.jpg/320px-Bella_Bergolts_The_Queen_Who_Never_Was.jpg",
  },
  {
    id: 42,
    name: "Viserys I",
    throne: king,
    gender: "male",
    dragon: "Balerion",
    culture: "Valyrian",
    Aliases: ["Viserys the Peaceful"],
    Born: "77 AC",
    Died: "129 AC",
    fid: 26,
    mid: 27,
    pids: [48, 60],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/7/7c/VISERYS_I.jpg",
  },
  {
    id: 43,
    name: "Daemon Targaryen",
    throne: king,
    gender: "male",
    dragon: "Caraxes",
    culture: "Valyrian",
    Aliases: ["The Rogue Prince"],
    Born: "81 AC",
    Died: "130 AC",
    fid: 26,
    mid: 27,
    pids: [57],
    sigil: targaryenSigil,
    img: "https://i.redd.it/j5qrcy4cj3c91.jpg",
  },
  {
    id: 44,
    name: "Aegon Targaryen",
    gender: "male",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "84 AC",
    Died: "85 AC",
    fid: 26,
    mid: 27,
    pids: [],
    sigil: targaryenSigil,
  },
  {
    id: 46,
    name: "Corlys Velaryon",
    gender: "male",
    dragon: null,
    culture: "Valyrian",
    Aliases: ["The Sea Snake"],
    Born: "53 AC",
    Died: "132 AC",
    fid: null,
    mid: null,
    pids: [41],
    sigil: velaryonSigil,
    img: "https://awoiaf.westeros.org/images/thumb/6/69/Z37tvql2m6m71.png/175px-Z37tvql2m6m71.png",
  },
  //   {
  //     id: 47,
  //     name: "Viserys I",
  //     throne: king,
  //     gender: "male",
  //     dragon: "Balerion",
  //     culture: "Valyrian",
  //     Aliases: ["Viserys the Peaceful"],
  //     Born: "77 AC",
  //     Died: "129 AC",
  //     fid: null,
  //     mid: null,
  //     pids: [40],
  //     sigil: targaryenSigil,
  //   },
  {
    id: 48,
    name: "Alicent Hightower",
    throne: queen,
    gender: "female",
    dragon: null,
    culture: "Reach",
    Aliases: ["The Queen in Chains"],
    Born: "77 AC",
    Died: "129 AC",
    fid: null,
    mid: null,
    pids: [42],
    sigil: hightowerSigil,
    img: "https://awoiaf.westeros.org/images/8/83/Queen_Alicent.jpg",
  },
  {
    id: 49,
    name: "Laena Velaryon",
    gender: "female",
    dragon: "Vhagar",
    culture: "Valyrian",
    Aliases: null,
    Born: "92 AC",
    Died: "120 AC",
    fid: 46,
    mid: 41,
    pids: [53],
    sigil: velaryonSigil,
    img: "https://awoiaf.westeros.org/images/thumb/6/6e/Laena_Velaryon_by_riotarttherite.png/187px-Laena_Velaryon_by_riotarttherite.png",
  },
  {
    id: 50,
    name: "Laenor Velaryon",
    gender: "male",
    dragon: "Seasmoke",
    culture: "Valyrian",
    Aliases: null,
    Born: "94 AC",
    Died: "120 AC",
    fid: 46,
    mid: 41,
    pids: [],
    sigil: velaryonSigil,
    img: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/35984d20-35e4-4767-aa6e-5be739dde8ea/dcc7rp2-d7b78e7c-788f-4759-9333-f26b33df3b98.jpg/v1/fill/w_1024,h_1536,q_75,strp/laenor_velaryon__game_of_thrones__by_manre_art_dcc7rp2-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTUzNiIsInBhdGgiOiJcL2ZcLzM1OTg0ZDIwLTM1ZTQtNDc2Ny1hYTZlLTViZTczOWRkZThlYVwvZGNjN3JwMi1kN2I3OGU3Yy03ODhmLTQ3NTktOTMzMy1mMjZiMzNkZjNiOTguanBnIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.YI3riI3D6Lws_w5_5-Df2009cpxUmjRKak5InWOgHUQ"
  },
  {
    id: 51,
    name: "Rhaenyra Targaryen",
    throne: queen,
    gender: "female",
    dragon: "Syrax",
    culture: "Valyrian",
    Aliases: ["The Realm's Delight"],
    Born: "97 AC",
    Died: "130 AC",
    fid: 42,
    mid: 60,
    pids: [52, 54],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/0/0c/Young_rhaenyra_targaryen.jpg/148px-Young_rhaenyra_targaryen.jpg",
  },
  {
    id: 52,
    name: "Daemon Targaryen",
    throne: king,
    gender: "male",
    dragon: "Caraxes",
    culture: "Valyrian",
    Aliases: ["The Rogue Prince"],
    Born: "81 AC",
    Died: "130 AC",
    fid: null,
    mid: null,
    pids: [51],
    sigil: targaryenSigil,
    img: "https://i.redd.it/j5qrcy4cj3c91.jpg",
  },
  {
    id: 53,
    name: "Daemon Targaryen",
    throne: king,
    gender: "male",
    dragon: "Caraxes",
    culture: "Valyrian",
    Aliases: ["The Rogue Prince"],
    Born: "81 AC",
    Died: "130 AC",
    fid: null,
    mid: null,
    pids: [49],
    sigil: targaryenSigil,
    img: "https://i.redd.it/j5qrcy4cj3c91.jpg",
  },
  {
    id: 54,
    name: "Laenor Velaryon",
    gender: "male",
    dragon: "Seasmoke",
    culture: "Valyrian",
    Aliases: null,
    Born: "94 AC",
    Died: "120 AC",
    fid: null,
    mid: null,
    pids: [51],
    sigil: velaryonSigil,
    img: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/35984d20-35e4-4767-aa6e-5be739dde8ea/dcc7rp2-d7b78e7c-788f-4759-9333-f26b33df3b98.jpg/v1/fill/w_1024,h_1536,q_75,strp/laenor_velaryon__game_of_thrones__by_manre_art_dcc7rp2-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTUzNiIsInBhdGgiOiJcL2ZcLzM1OTg0ZDIwLTM1ZTQtNDc2Ny1hYTZlLTViZTczOWRkZThlYVwvZGNjN3JwMi1kN2I3OGU3Yy03ODhmLTQ3NTktOTMzMy1mMjZiMzNkZjNiOTguanBnIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.YI3riI3D6Lws_w5_5-Df2009cpxUmjRKak5InWOgHUQ"
  },
  {
    id: 55,
    name: "Jacaerys Velaryon",
    gender: "male",
    dragon: "Vermax",
    culture: "Valyrian",
    Aliases: ["Jace Strong"],
    Born: "114 AC",
    Died: "130 AC",
    fid: 54,
    mid: 51,
    pids: [],
    sigil: velaryonSigil,
    img: "https://64.media.tumblr.com/4bc69905ccc7a7b7bedb038e905b65da/3ed7509d1b323ae6-28/s540x810/d44d16ed3e975724bdee2216bde7c986a8cd8848.jpg"
  },
  {
    id: 58,
    name: "Lucerys Velaryon",
    gender: "male",
    dragon: "Arrax",
    culture: "Valyrian",
    Aliases: ["Little Luke Strong"],
    Born: "115 AC",
    Died: "129 AC",
    fid: 54,
    mid: 51,
    pids: [],
    sigil: velaryonSigil,
    img: "https://64.media.tumblr.com/f896f0074502074a6c245d31f111e87e/dddfc9b4eb927117-13/s1280x1920/b41793d9ce366ca65a1c4dbd8e0432302ba3497a.jpg"
  },
  {
    id: 59,
    name: "Joffrey Velaryon",
    gender: "male",
    dragon: "Tyraxes",
    culture: "Valyrian",
    Aliases: ["Joff"],
    Born: "117 AC",
    Died: "130 AC",
    fid: 54,
    mid: 51,
    pids: [],
    sigil: velaryonSigil,
    img: "http://pm1.narvii.com/6509/9c31f71f3ea8f3444801b5408e3f25dcab0c49c3_00.jpg"
  },
  {
    id: 56,
    name: "Aegon III",
    throne: king,
    gender: "male",
    dragon: "Stormcloud",
    culture: "Valyrian",
    Aliases: ["Aegon the Dragonbane"],
    Born: "120 AC",
    Died: "157 AC",
    fid: 52,
    mid: 51,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/0/05/AEGON_III.jpg",
  },
  {
    id: 61,
    name: "Viserys II",
    throne: king,
    gender: "male",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "122 AC",
    Died: "172 AC",
    fid: 52,
    mid: 51,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/a/ad/VISERYS_II.jpg",
  },
  {
    id: 62,
    name: "Visenya Targaryen",
    gender: "female",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "129 AC",
    Died: "129 AC",
    fid: 52,
    mid: 51,
    pids: [],
    sigil: targaryenSigil,
  },
  {
    id: 57,
    name: "Rhea Royce",
    gender: "female",
    dragon: null,
    culture: "Valemen",
    Aliases: ["Bronze Bitch"],
    Born: "",
    Died: "115 AC",
    fid: null,
    mid: null,
    pids: [43],
    sigil: royceSigil,
    img: "https://external-preview.redd.it/2iU15JDM5mtZfNv9IKKPYolVjPH1T8y-vDbJGU37nHs.jpg?width=640&crop=smart&auto=webp&s=cb3e9519a3f5ba6d14c1b92d4091a4a62f171cac"
  },
  {
    id: 60,
    name: "Aemma Arryn",
    throne: queen,
    gender: "female",
    dragon: null,
    culture: "Valemen",
    Aliases: null,
    Born: "82 AC",
    Died: "105 AC",
    fid: null,
    mid: null,
    pids: [42],
    sigil: arrynSigil,
    img: "https://awoiaf.westeros.org/images/thumb/9/9f/Aemma_Arryn_and_Rhaenyra_Targaryen_by_Fkaluis.jpg/218px-Aemma_Arryn_and_Rhaenyra_Targaryen_by_Fkaluis.jpg",
  },
  {
    id: 63,
    name: "Baelon Targaryen",
    gender: "male",
    dragon: null,
    culture: "Valyrian",
    Aliases: ["Heir for a Day"],
    Born: "105 AC",
    Died: "105 AC",
    fid: 42,
    mid: 60,
    pids: [],
    sigil: targaryenSigil,
  },
  {
    id: 65,
    name: "Aegon II",
    throne: king,
    gender: "male",
    dragon: "Sunfyre",
    culture: "Valyrian",
    Aliases: ["Aegon the Elder"],
    Born: "107 AC",
    Died: "131 AC",
    fid: 42,
    mid: 48,
    pids: [71],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/4/46/AEGON_II.jpg",
  },
  {
    id: 66,
    name: "Helaena Targaryen",
    throne: queen,
    gender: "female",
    dragon: "Dreamfyre",
    culture: "Valyrian",
    Aliases: null,
    Born: "109 AC",
    Died: "130 AC",
    fid: 42,
    mid: 48,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/f/f9/Helaena_Targaryen_by_Hylora.png/221px-Helaena_Targaryen_by_Hylora.png",
  },
  {
    id: 67,
    name: "Aemond Targaryen",
    gender: "male",
    dragon: "Vhagar",
    culture: "Valyrian",
    Aliases: ["Aemond One-Eye"],
    Born: "110 AC",
    Died: "130 AC",
    fid: 42,
    mid: 48,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/1/12/Aemond_Targaryen_by_Shen_Fei.jpg/183px-Aemond_Targaryen_by_Shen_Fei.jpg",
  },
  {
    id: 68,
    name: "Daeron Targaryen",
    gender: "male",
    dragon: "Tessarion",
    culture: "Valyrian",
    Aliases: ["Daeron the Daring"],
    Born: "114 AC",
    Died: "130 AC",
    fid: 42,
    mid: 48,
    pids: [],
    sigil: targaryenSigil,
  },
  {
    id: 69,
    name: "Baela Targaryen",
    gender: "female",
    dragon: "Moondancer",
    culture: "Valyrian",
    Aliases: ["Dragon Twin"],
    Born: "116 AC",
    Died: "136-176 AC",
    fid: 53,
    mid: 49,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/c/cd/Baela_Targaryen_by_Naomimakesart.png/184px-Baela_Targaryen_by_Naomimakesart.png",
  },
  {
    id: 70,
    name: "Rhaena Targaryen",
    gender: "female",
    dragon: "Morning",
    culture: "Valyrian",
    Aliases: ["Dragon Twin"],
    Born: "116 AC",
    Died: "136-176 AC",
    fid: 53,
    mid: 49,
    pids: [],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/b/b7/Rhaena_Targaryen_%28daughter_of_Daemon%29_by_Naomimakesart.png/184px-Rhaena_Targaryen_%28daughter_of_Daemon%29_by_Naomimakesart.png",
  },
  {
    id: 71,
    name: "Helaena Targaryen",
    throne: queen,
    gender: "female",
    dragon: "Dreamfyre",
    culture: "Valyrian",
    Aliases: null,
    Born: "109 AC",
    Died: "130 AC",
    fid: null,
    mid: null,
    pids: [65],
    sigil: targaryenSigil,
    img: "https://awoiaf.westeros.org/images/thumb/f/f9/Helaena_Targaryen_by_Hylora.png/221px-Helaena_Targaryen_by_Hylora.png",
  },
  {
    id: 72,
    name: "Jaehaerys Targaryen",
    gender: "male",
    dragon: "Shrykos",
    culture: "Valyrian",
    Aliases: null,
    Born: "123 AC",
    Died: "129 AC",
    fid: 65,
    mid: 71,
    pids: [],
    sigil: targaryenSigil,
  },
  {
    id: 73,
    name: "Jaehaera Targaryen",
    throne: queen,
    gender: "female",
    dragon: "Morghul",
    culture: "Valyrian",
    Aliases: null,
    Born: "123 AC",
    Died: "133 AC",
    fid: 65,
    mid: 71,
    pids: [],
    sigil: targaryenSigil,
  },
  {
    id: 74,
    name: "Maelor Targaryen",
    gender: "male",
    dragon: null,
    culture: "Valyrian",
    Aliases: null,
    Born: "127 AC",
    Died: "130 AC",
    fid: 65,
    mid: 71,
    pids: [],
    sigil: targaryenSigil,
  },
];
